image:
  repository: "linuxserver/jackett"
  pullPolicy: "IfNotPresent"
  tag: "0.24.1614@sha256:9004c9d945e627f3e536bd1cef96b75a4d8bccd4d1adaa7a09de9d51715bd08d"
service:
  main:
    ports:
      main:
        protocol: http
        targetPort: 9117
        port: 9117
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              path: "/health"
            readiness:
              path: "/health"
            startup:
              path: "/health"
persistence:
  config:
    enabled: true
    mountPath: "/config"
portal:
  open:
    enabled: true
