image:
  repository: "linuxserver/jackett"
  pullPolicy: "IfNotPresent"
  tag: "0.24.2360@sha256:2434d2d33da5a75dd6846baa644a6e06f2d0bc3aa819350624285adadc9134f8"
service:
  main:
    ports:
      main:
        protocol: http
        targetPort: 9117
        port: 9117
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              path: "/health"
            readiness:
              path: "/health"
            startup:
              path: "/health"
persistence:
  config:
    enabled: true
    mountPath: "/config"
portal:
  open:
    enabled: true
