image:
  repository: "linuxserver/jackett"
  pullPolicy: "IfNotPresent"
  tag: "0.24.2187@sha256:396edde9d6e23d2acacd368edba590bf4c2318703de9642d22589d99373525a7"
service:
  main:
    ports:
      main:
        protocol: http
        targetPort: 9117
        port: 9117
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              path: "/health"
            readiness:
              path: "/health"
            startup:
              path: "/health"
persistence:
  config:
    enabled: true
    mountPath: "/config"
portal:
  open:
    enabled: true
