image:
  repository: "linuxserver/jackett"
  pullPolicy: "IfNotPresent"
  tag: "0.24.1528@sha256:44ba8b78a32df06f00db1d809ee81ddfc5483a798c7d62f0e4357b1174cbab74"
service:
  main:
    ports:
      main:
        protocol: http
        targetPort: 9117
        port: 9117
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              path: "/health"
            readiness:
              path: "/health"
            startup:
              path: "/health"
persistence:
  config:
    enabled: true
    mountPath: "/config"
portal:
  open:
    enabled: true
